name: Build Executable
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: echo "Building an executable of Whisperr on new Version"
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Build with PyInstaller
        run: pyinstaller --onefile --name whisperr whisperr.py
      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: whisperr_installer.iss
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/whisperr.exe
